# Generated by Django 4.2.7 on 2025-10-13 18:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=20, unique=True, verbose_name='Référence')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre du projet')),
                ('description', models.TextField(verbose_name='Description détaillée')),
                ('taux_rendement', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(100)], verbose_name='Taux de rendement (%)')),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(100000)], verbose_name='Montant total (FCFA)')),
                ('montant_collecte', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Montant collecté (FCFA)')),
                ('duree', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)], verbose_name='Durée (mois)')),
                ('date_debut', models.DateField(verbose_name='Date de début prévue')),
                ('date_fin', models.DateField(verbose_name='Date de fin prévue')),
                ('localisation', models.CharField(max_length=200, verbose_name='Localisation')),
                ('ville', models.CharField(default='Ouagadougou', max_length=100, verbose_name='Ville')),
                ('region', models.CharField(default='Centre', max_length=100, verbose_name='Région')),
                ('statut', models.CharField(choices=[('EN_ATTENTE_VALIDATION', 'En attente de validation'), ('VALIDE', 'Validé'), ('REFUSE', 'Refusé'), ('EN_COURS_FINANCEMENT', 'En cours de financement'), ('FINANCE', 'Financé'), ('EN_REALISATION', 'En réalisation'), ('TERMINE', 'Terminé'), ('ANNULE', 'Annulé')], default='EN_ATTENTE_VALIDATION', max_length=25, verbose_name='Statut du projet')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('motif_refus', models.TextField(blank=True, verbose_name='Motif de refus')),
                ('administrateur_validateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projets_valides', to=settings.AUTH_USER_MODEL, verbose_name='Administrateur validateur')),
                ('promoteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projets', to=settings.AUTH_USER_MODEL, verbose_name='Promoteur')),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='CompteRendu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('contenu', models.TextField(verbose_name='Contenu')),
                ('date_publication', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de publication')),
                ('avancement', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Avancement (%)')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comptes_rendus', to='projects.projet', verbose_name='Projet')),
            ],
            options={
                'verbose_name': 'Compte rendu',
                'verbose_name_plural': 'Comptes rendus',
                'ordering': ['-date_publication'],
            },
        ),
        migrations.CreateModel(
            name='Etape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name="Titre de l'étape")),
                ('description', models.TextField(verbose_name='Description')),
                ('ordre', models.IntegerField(verbose_name='Ordre')),
                ('date_publication', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de publication')),
                ('date_realisation', models.DateTimeField(blank=True, null=True, verbose_name='Date de réalisation')),
                ('terminee', models.BooleanField(default=False, verbose_name='Terminée')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes', to='projects.projet', verbose_name='Projet')),
            ],
            options={
                'verbose_name': 'Étape',
                'verbose_name_plural': 'Étapes',
                'ordering': ['ordre'],
                'unique_together': {('projet', 'ordre')},
            },
        ),
    ]
