# Generated by Django 4.2.7 on 2025-10-30 11:47

import apps.projects.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='adresse_complete',
            field=models.TextField(blank=True, verbose_name='Adresse complète'),
        ),
        migrations.AddField(
            model_name='projet',
            name='date_publication',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de publication'),
        ),
        migrations.AddField(
            model_name='projet',
            name='montant_min_investissement',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=10, validators=[django.core.validators.MinValueValidator(10000)], verbose_name="Montant minimum d'investissement (FCFA)"),
        ),
        migrations.AddField(
            model_name='projet',
            name='resume',
            field=models.TextField(default='Aucun résumé'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EN_ATTENTE_VALIDATION', 'En attente de validation'), ('VALIDE', 'Validé'), ('REFUSE', 'Refusé'), ('EN_COURS_FINANCEMENT', 'En cours de financement'), ('FINANCE', 'Financé'), ('EN_REALISATION', 'En réalisation'), ('TERMINE', 'Terminé'), ('ANNULE', 'Annulé')], default='BROUILLON', max_length=25, verbose_name='Statut du projet'),
        ),
        migrations.CreateModel(
            name='ImageProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.projects.models.projet_image_path, verbose_name='Image')),
                ('legende', models.CharField(blank=True, max_length=200, verbose_name='Légende')),
                ('est_principale', models.BooleanField(default=False, verbose_name='Image principale')),
                ('date_ajout', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'ajout")),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.projet', verbose_name='Projet')),
            ],
            options={
                'verbose_name': 'Image de projet',
                'verbose_name_plural': 'Images de projet',
                'ordering': ['-est_principale', 'date_ajout'],
            },
        ),
        migrations.CreateModel(
            name='DocumentProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('ETUDE_FACTIBILITE', 'Étude de faisabilité'), ('PLAN_ARCHITECTURAL', 'Plan architectural'), ('PERMIS_CONSTRUIRE', 'Permis de construire'), ('CONTRAT', 'Contrat'), ('RAPPORT', 'Rapport'), ('AUTRE', 'Autre')], max_length=50, verbose_name='Type de document')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du document')),
                ('fichier', models.FileField(upload_to=apps.projects.models.projet_document_path, verbose_name='Fichier')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('date_ajout', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'ajout")),
                ('est_public', models.BooleanField(default=True, verbose_name='Document public')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.projet', verbose_name='Projet')),
            ],
            options={
                'verbose_name': 'Document de projet',
                'verbose_name_plural': 'Documents de projet',
                'ordering': ['-date_ajout'],
            },
        ),
    ]
