# Generated by Django 4.2.7 on 2025-11-03 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projet_adresse_complete_projet_date_publication_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EN_ATTENTE_VALIDATION', 'En attente de validation'), ('VALIDE', 'Validé'), ('REFUSE', 'Refusé'), ('EN_COURS_FINANCEMENT', 'En cours de financement'), ('FINANCE', 'Financé'), ('EN_REALISATION', 'En réalisation'), ('TERMINE', 'Terminé'), ('ANNULE', 'Annulé')], default='EN_ATTENTE_VALIDATION', max_length=25, verbose_name='Statut du projet'),
        ),
        migrations.CreateModel(
            name='CompteRenduImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='comptes_rendus/%Y/%m/')),
                ('legende', models.CharField(blank=True, max_length=200)),
                ('compte_rendu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.compterendu')),
            ],
        ),
    ]
