# Generated by Django 4.2.7 on 2025-11-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_projet_statut_compterenduimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='etape',
            name='date_prevue',
            field=models.DateField(blank=True, null=True, verbose_name='Date prévue'),
        ),
        migrations.AddField(
            model_name='projet',
            name='date_debut_execution',
            field=models.DateField(blank=True, null=True, verbose_name="Date de début d'exécution"),
        ),
        migrations.AddField(
            model_name='projet',
            name='etapes_definies',
            field=models.BooleanField(default=False, verbose_name='Étapes définies'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EN_ATTENTE_VALIDATION', 'En attente de validation'), ('A_COMPLETER', 'À compléter'), ('VALIDE', 'Validé'), ('REFUSE', 'Refusé'), ('EN_CAMPAGNE', 'En campagne de financement'), ('FINANCE', 'Financé'), ('EN_COURS_EXECUTION', "En cours d'exécution"), ('TERMINE', 'Terminé'), ('ANNULE', 'Annulé')], default='EN_ATTENTE_VALIDATION', max_length=25, verbose_name='Statut du projet'),
        ),
        migrations.DeleteModel(
            name='CompteRenduImage',
        ),
    ]
