# Generated by Django 4.2.7 on 2025-11-06 22:08

import apps.projects.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_etape_date_prevue_projet_date_debut_execution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='categorie',
            field=models.CharField(choices=[('RESIDENTIEL', 'Résidentiel'), ('COMMERCIAL', 'Commercial'), ('BUREAUX', 'Bureaux'), ('INDUSTRIEL', 'Industriel'), ('MIXTE', 'Mixte'), ('AUTRE', 'Autre')], default='RESIDENTIEL', max_length=50, verbose_name='Type de projet immobilier'),
        ),
        migrations.AddField(
            model_name='projet',
            name='image_garde',
            field=models.ImageField(blank=True, null=True, upload_to=apps.projects.models.projet_image_garde_path, verbose_name='Image de garde'),
        ),
        migrations.CreateModel(
            name='DocumentObligatoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('ETUDE_FACTIBILITE', 'Étude de faisabilité'), ('PLAN_ARCHITECTURAL', 'Plan architectural'), ('PERMIS_CONSTRUIRE', 'Permis de construire'), ('BUSINESS_PLAN', 'Business plan'), ('TECHNIQUE', 'Document technique'), ('AUTRE', 'Autre')], max_length=50, verbose_name='Type de document')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du document')),
                ('fichier', models.FileField(upload_to=apps.projects.models.document_obligatoire_path, verbose_name='Fichier')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('est_obligatoire', models.BooleanField(default=True, verbose_name='Document obligatoire')),
                ('date_depot', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de dépôt')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_obligatoires', to='projects.projet', verbose_name='Projet')),
            ],
            options={
                'verbose_name': 'Document obligatoire',
                'verbose_name_plural': 'Documents obligatoires',
                'ordering': ['type_document'],
            },
        ),
    ]
