# Generated by Django 4.2.7 on 2025-11-06 23:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_projet_categorie_projet_image_garde_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='duree_campagne',
            field=models.IntegerField(default=60, help_text='Durée de la campagne de financement en jours (30 à 365 jours)', validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(365)], verbose_name='Durée de campagne (jours)'),
        ),
    ]
