# Generated by Django 4.2.7 on 2025-11-19 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0006_projet_duree_campagne'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentobligatoire',
            name='administrateur_validateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_obligatoires_valides', to=settings.AUTH_USER_MODEL, verbose_name='Administrateur validateur'),
        ),
        migrations.AddField(
            model_name='documentobligatoire',
            name='date_validation',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de validation'),
        ),
        migrations.AddField(
            model_name='documentobligatoire',
            name='est_rejete',
            field=models.BooleanField(default=False, verbose_name='Rejeté'),
        ),
        migrations.AddField(
            model_name='documentobligatoire',
            name='est_valide',
            field=models.BooleanField(default=False, verbose_name='Validé'),
        ),
        migrations.AddField(
            model_name='documentobligatoire',
            name='motif_rejet',
            field=models.TextField(blank=True, verbose_name='Motif de rejet'),
        ),
    ]
