# Generated by Django 4.2.7 on 2025-11-19 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_documentobligatoire_administrateur_validateur_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentobligatoire',
            name='administrateur_validateur',
        ),
        migrations.RemoveField(
            model_name='documentobligatoire',
            name='date_validation',
        ),
        migrations.RemoveField(
            model_name='documentobligatoire',
            name='est_rejete',
        ),
        migrations.RemoveField(
            model_name='documentobligatoire',
            name='est_valide',
        ),
        migrations.RemoveField(
            model_name='documentobligatoire',
            name='motif_rejet',
        ),
    ]
