# Generated by Django 4.2.7 on 2025-12-24 01:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_projet_nombre_total_parts_projet_seuil_declenchement'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='prix_unitaire',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Prix fixé manuellement par le promoteur pour chaque part', max_digits=15, null=True, verbose_name="Prix unitaire d'une part (FCFA)"),
        ),
        migrations.AlterField(
            model_name='projet',
            name='montant_min_investissement',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10, validators=[django.core.validators.MinValueValidator(100)], verbose_name="Montant minimum d'investissement (FCFA)"),
        ),
        migrations.AlterField(
            model_name='projet',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE_VALIDATION', 'En attente de validation'), ('A_COMPLETER', 'À compléter'), ('VALIDE', 'Validé'), ('REFUSE', 'Refusé'), ('EN_CAMPAGNE', 'En campagne de financement'), ('FINANCE', 'Financé'), ('EN_COURS_EXECUTION', "En cours d'exécution"), ('TERMINE', 'Terminé'), ('ANNULE', 'Annulé')], default='EN_ATTENTE_VALIDATION', max_length=25, verbose_name='Statut du projet'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='taux_rendement',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(100)], verbose_name='Taux de rendement (%)'),
        ),
    ]
