# Generated by Django 4.2.7 on 2025-12-24 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_projet_prix_unitaire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EN_ATTENTE_VALIDATION', 'En attente de validation'), ('A_COMPLETER', 'À compléter'), ('VALIDE', 'Validé'), ('REFUSE', 'Refusé'), ('EN_CAMPAGNE', 'En campagne de financement'), ('FINANCE', 'Financé'), ('EN_COURS_EXECUTION', "En cours d'exécution"), ('TERMINE', 'Terminé'), ('ANNULE', 'Annulé')], default='EN_ATTENTE_VALIDATION', max_length=25, verbose_name='Statut du projet'),
        ),
    ]
