# Generated by Django 4.2.7 on 2025-12-24 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_alter_projet_statut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projet',
            name='taux_rendement',
        ),
    ]
