# Generated by Django 4.2.7 on 2025-12-26 23:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_remove_projet_taux_rendement'),
    ]

    operations = [
        migrations.AddField(
            model_name='etape',
            name='duree_estimee',
            field=models.IntegerField(blank=True, help_text='Durée estimée en mois', null=True, verbose_name='Durée estimée (mois)'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='duree',
            field=models.IntegerField(help_text='Durée prévisionnelle de réalisation en mois', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)], verbose_name='Durée de réalisation (mois)'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='duree_campagne',
            field=models.IntegerField(default=3, help_text='Durée de la campagne de collecte en mois (1 à 24 mois)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)], verbose_name='Durée de collecte (mois)'),
        ),
    ]
