# Generated by Django 4.2.7 on 2025-12-27 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_etape_duree_estimee_alter_projet_duree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='categorie',
            field=models.CharField(choices=[('RESIDENTIEL', 'Résidentiel'), ('COMMERCIAL', 'Commercial'), ('BUREAUX', 'Bureaux'), ('INDUSTRIEL', 'Industriel')], default='RESIDENTIEL', max_length=50, verbose_name='Type de projet immobilier'),
        ),
    ]
