# Generated by Django 4.2.7 on 2025-12-29 17:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_alter_projet_categorie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etape',
            name='date_prevue',
        ),
        migrations.AddField(
            model_name='etape',
            name='date_debut',
            field=models.DateField(blank=True, null=True, verbose_name='Date de début prévue'),
        ),
        migrations.AlterField(
            model_name='etape',
            name='duree_estimee',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Durée estimée (mois)'),
        ),
    ]
