# Generated by Django 4.2.7 on 2025-12-30 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_remove_etape_date_prevue_etape_date_debut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='document_financier_motif_rejet',
            field=models.TextField(blank=True, verbose_name='Motif de rejet document financier'),
        ),
        migrations.AddField(
            model_name='projet',
            name='document_financier_rejete',
            field=models.BooleanField(default=False, verbose_name='Document financier rejeté'),
        ),
        migrations.AddField(
            model_name='projet',
            name='document_financier_valide',
            field=models.BooleanField(default=False, verbose_name='Document financier validé'),
        ),
        migrations.AddField(
            model_name='projet',
            name='document_foncier_motif_rejet',
            field=models.TextField(blank=True, verbose_name='Motif de rejet document foncier'),
        ),
        migrations.AddField(
            model_name='projet',
            name='document_foncier_rejete',
            field=models.BooleanField(default=False, verbose_name='Document foncier rejeté'),
        ),
        migrations.AddField(
            model_name='projet',
            name='document_foncier_valide',
            field=models.BooleanField(default=False, verbose_name='Document foncier validé'),
        ),
        migrations.AddField(
            model_name='projet',
            name='document_technique_motif_rejet',
            field=models.TextField(blank=True, verbose_name='Motif de rejet document technique'),
        ),
        migrations.AddField(
            model_name='projet',
            name='document_technique_rejete',
            field=models.BooleanField(default=False, verbose_name='Document technique rejeté'),
        ),
        migrations.AddField(
            model_name='projet',
            name='document_technique_valide',
            field=models.BooleanField(default=False, verbose_name='Document technique validé'),
        ),
    ]
