# Generated by Django 4.2.7 on 2026-01-02 11:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_projet_document_financier_motif_rejet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='nombre_total_parts',
            field=models.IntegerField(default=1000, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(100000)], verbose_name='Nombre total de parts'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='seuil_declenchement',
            field=models.DecimalField(decimal_places=2, default=100.0, help_text='Seuil de déclenchement fixé à 100%', max_digits=5, verbose_name='Seuil de déclenchement'),
        ),
    ]
