# Generated by Django 4.2.7 on 2026-01-02 11:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_alter_projet_nombre_total_parts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='nombre_total_parts',
            field=models.IntegerField(default=1000, help_text="Définit le nombre de parts disponibles pour l'investissement", validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(100000)], verbose_name='Nombre total de parts'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='seuil_declenchement',
            field=models.DecimalField(decimal_places=2, default=70.0, help_text='Pourcentage minimal de financement requis pour démarrer le projet', max_digits=5, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(100)], verbose_name='Seuil de déclenchement (%)'),
        ),
    ]
