# Generated by Django 4.2.7 on 2026-01-02 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_alter_projet_nombre_total_parts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etape',
            name='statut',
            field=models.CharField(choices=[('A_VENIR', 'À venir'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée'), ('RETARD', 'En retard')], default='A_VENIR', max_length=20, verbose_name="Statut de l'étape"),
        ),
    ]
