# Generated by Django 4.2.7 on 2026-01-03 02:11

import apps.projects.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0020_etape_statut'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageCompteRendu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.projects.models.image_compte_rendu_path, validators=[apps.projects.models.validate_image_size], verbose_name='Fichier image')),
                ('legende', models.CharField(blank=True, help_text="Description courte de l'image", max_length=200, verbose_name='Légende')),
                ('ordre', models.IntegerField(default=0, help_text="Pour organiser l'ordre des images", verbose_name="Ordre d'affichage")),
                ('date_upload', models.DateTimeField(auto_now_add=True, verbose_name="Date d'upload")),
                ('est_valide', models.BooleanField(default=True, help_text="L'image a été vérifiée par l'administration", verbose_name='Image valide')),
            ],
            options={
                'verbose_name': 'Image de compte rendu',
                'verbose_name_plural': 'Images de compte rendu',
                'ordering': ['ordre', 'date_upload'],
            },
        ),
        migrations.AlterModelOptions(
            name='compterendu',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Compte rendu', 'verbose_name_plural': 'Comptes rendus'},
        ),
        migrations.AddField(
            model_name='compterendu',
            name='administrateur_validateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comptes_rendus_valides', to=settings.AUTH_USER_MODEL, verbose_name='Administrateur validateur'),
        ),
        migrations.AddField(
            model_name='compterendu',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création'),
        ),
        migrations.AddField(
            model_name='compterendu',
            name='date_validation',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de validation'),
        ),
        migrations.AddField(
            model_name='compterendu',
            name='etape',
            field=models.ForeignKey(blank=True, help_text='Optionnel : lier ce compte rendu à une étape spécifique', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comptes_rendus', to='projects.etape', verbose_name='Étape concernée'),
        ),
        migrations.AddField(
            model_name='compterendu',
            name='motif_rejet',
            field=models.TextField(blank=True, verbose_name='Motif de rejet'),
        ),
        migrations.AddField(
            model_name='compterendu',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE_VALIDATION', 'En attente de validation'), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté')], default='EN_ATTENTE_VALIDATION', max_length=30, verbose_name='Statut de validation'),
        ),
        migrations.AlterField(
            model_name='compterendu',
            name='date_publication',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de publication'),
        ),
        migrations.AddIndex(
            model_name='compterendu',
            index=models.Index(fields=['projet', 'statut'], name='projects_co_projet__2feec6_idx'),
        ),
        migrations.AddIndex(
            model_name='compterendu',
            index=models.Index(fields=['date_creation'], name='projects_co_date_cr_4cae75_idx'),
        ),
        migrations.AddIndex(
            model_name='compterendu',
            index=models.Index(fields=['statut'], name='projects_co_statut_a917f5_idx'),
        ),
        migrations.AddField(
            model_name='imagecompterendu',
            name='compte_rendu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.compterendu', verbose_name='Compte rendu'),
        ),
        migrations.AddIndex(
            model_name='imagecompterendu',
            index=models.Index(fields=['compte_rendu', 'ordre'], name='projects_im_compte__963da6_idx'),
        ),
        migrations.AddIndex(
            model_name='imagecompterendu',
            index=models.Index(fields=['compte_rendu', 'est_valide'], name='projects_im_compte__ad25a9_idx'),
        ),
    ]
