# Generated by Django 4.2.7 on 2026-01-04 23:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0021_imagecompterendu_alter_compterendu_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeModificationCompteRendu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaires', models.TextField(verbose_name='Commentaires pour modification')),
                ('date_demande', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de la demande')),
                ('date_modification', models.DateTimeField(blank=True, null=True, verbose_name='Date de modification')),
                ('est_resolue', models.BooleanField(default=False, verbose_name='Demande résolue')),
                ('administrateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_modification_faites', to=settings.AUTH_USER_MODEL, verbose_name='Administrateur')),
                ('compte_rendu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_modification', to='projects.compterendu', verbose_name='Compte rendu')),
            ],
            options={
                'verbose_name': 'Demande de modification de compte rendu',
                'verbose_name_plural': 'Demandes de modification de compte rendu',
                'ordering': ['-date_demande'],
            },
        ),
    ]
