# Generated by Django 4.2.7 on 2026-01-07 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_demandemodificationcompterendu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compterendu',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE_VALIDATION', 'En attente de validation'), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté'), ('A_MODIFIER', 'À modifier')], default='EN_ATTENTE_VALIDATION', max_length=30, verbose_name='Statut de validation'),
        ),
    ]
