# Generated by Django 4.2.7 on 2026-01-09 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_alter_compterendu_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='parts_vendues',
            field=models.PositiveIntegerField(default=0, verbose_name='Parts vendues'),
        ),
    ]
