# Generated by Django 4.2.7 on 2026-01-16 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_projet_parts_vendues'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='motif_suspension',
            field=models.TextField(blank=True, verbose_name='Motif de suspension'),
        ),
        migrations.AddField(
            model_name='projet',
            name='statut_precedent',
            field=models.CharField(blank=True, choices=[('BROUILLON', 'Brouillon'), ('EN_ATTENTE_VALIDATION', 'En attente de validation'), ('A_COMPLETER', 'À compléter'), ('VALIDE', 'Validé'), ('REFUSE', 'Refusé'), ('EN_CAMPAGNE', 'En campagne de financement'), ('FINANCE', 'Financé'), ('EN_COURS_EXECUTION', "En cours d'exécution"), ('TERMINE', 'Terminé'), ('ANNULE', 'Annulé')], max_length=25, null=True, verbose_name='Statut précédent avant suspension'),
        ),
    ]
