# Generated by Django 4.2.7 on 2026-01-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_projet_motif_suspension_projet_statut_precedent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EN_ATTENTE_VALIDATION', 'En attente de validation'), ('VALIDE', 'Validé'), ('REFUSE', 'Refusé'), ('EN_CAMPAGNE', 'En campagne'), ('FINANCE', 'Financé'), ('EN_COURS_EXECUTION', 'En cours d’exécution'), ('TERMINE', 'Terminé'), ('SUSPENDU', 'Suspendu')], default='EN_ATTENTE_VALIDATION', max_length=25, verbose_name='Statut du projet'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='statut_precedent',
            field=models.CharField(blank=True, choices=[('BROUILLON', 'Brouillon'), ('EN_ATTENTE_VALIDATION', 'En attente de validation'), ('VALIDE', 'Validé'), ('REFUSE', 'Refusé'), ('EN_CAMPAGNE', 'En campagne'), ('FINANCE', 'Financé'), ('EN_COURS_EXECUTION', 'En cours d’exécution'), ('TERMINE', 'Terminé'), ('SUSPENDU', 'Suspendu')], max_length=25, null=True, verbose_name='Statut précédent avant suspension'),
        ),
    ]
