# Generated by Django 4.2.7 on 2026-01-19 14:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_alter_projet_statut_alter_projet_statut_precedent'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='nombre_min_parts',
            field=models.PositiveIntegerField(default=1, help_text="Nombre minimum de parts qu'un investisseur doit souscrire", validators=[django.core.validators.MinValueValidator(1)], verbose_name='Nombre minimum de parts par investisseur'),
        ),
    ]
