# Generated by Django 4.2.7 on 2026-01-19 14:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_projet_nombre_min_parts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='nombre_min_parts',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Nombre minimum de parts à acheter'),
        ),
    ]
