# Generated by Django 4.2.7 on 2025-10-13 18:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=20, unique=True, verbose_name='Référence')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(10000)], verbose_name='Montant investi (FCFA)')),
                ('date_investissement', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'investissement")),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('CONFIRME', 'Confirmé'), ('ANNULE', 'Annulé')], default='EN_ATTENTE', max_length=15, verbose_name="Statut de l'investissement")),
                ('origine_fonds', models.CharField(choices=[('SALAIRE', 'Salaire'), ('BUSINESS', 'Activité commerciale'), ('HERITAGE', 'Héritage'), ('EPARGNE', 'Épargne'), ('DIASPORA', 'Fonds de la diaspora'), ('AUTRE', 'Autre')], max_length=100, verbose_name='Origine des fonds')),
                ('contrat_accepte', models.BooleanField(default=False, verbose_name='Contrat accepté')),
                ('date_contrat', models.DateTimeField(blank=True, null=True, verbose_name="Date d'acceptation du contrat")),
                ('investisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investissements', to=settings.AUTH_USER_MODEL, verbose_name='Investisseur')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investissements', to='projects.projet', verbose_name='Projet')),
            ],
            options={
                'verbose_name': 'Investissement',
                'verbose_name_plural': 'Investissements',
                'ordering': ['-date_investissement'],
                'unique_together': {('investisseur', 'projet')},
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=20, unique=True, verbose_name='Référence')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Montant (FCFA)')),
                ('date_transaction', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de transaction')),
                ('type', models.CharField(choices=[('INVESTISSEMENT', 'Investissement'), ('REMBOURSEMENT', 'Remboursement'), ('RENDEMENT', 'Rendement')], max_length=15, verbose_name='Type de transaction')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDEE', 'Validée'), ('ECHOUEE', 'Échouée'), ('ANNULEE', 'Annulée')], default='EN_ATTENTE', max_length=15, verbose_name='Statut de la transaction')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('numero_transaction_bancaire', models.CharField(blank=True, max_length=50, verbose_name='Numéro de transaction bancaire')),
                ('investissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='investments.investissement', verbose_name='Investissement')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-date_transaction'],
            },
        ),
    ]
