# Generated by Django 4.2.7 on 2025-11-26 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='mode_paiement',
            field=models.CharField(blank=True, choices=[('ORANGE_MONEY', 'Orange Money'), ('MOOV_MONEY', 'Moov Money'), ('WAVE', 'Wave'), ('CARTE_BANCAIRE', 'Carte Bancaire'), ('VIREMENT', 'Virement Bancaire')], max_length=20, verbose_name='Mode de paiement'),
        ),
    ]
