# Generated by Django 4.2.7 on 2026-01-08 20:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_transaction_mode_paiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='investissement',
            name='nombre_parts',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Nombre de parts détenues'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='investissement',
            name='contrat_accepte',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='investissement',
            name='date_contrat',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
