# Generated by Django 4.2.7 on 2026-01-09 09:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_alter_compterendu_statut'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investments', '0003_investissement_nombre_parts_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investissement',
            options={'ordering': ['-date_investissement']},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date_transaction']},
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='numero_transaction_bancaire',
        ),
        migrations.AlterField(
            model_name='investissement',
            name='date_investissement',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='investissement',
            name='investisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investissements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='investissement',
            name='origine_fonds',
            field=models.CharField(choices=[('SALAIRE', 'Salaire'), ('BUSINESS', 'Activité commerciale'), ('HERITAGE', 'Héritage'), ('EPARGNE', 'Épargne'), ('DIASPORA', 'Fonds de la diaspora'), ('AUTRE', 'Autre')], max_length=100),
        ),
        migrations.AlterField(
            model_name='investissement',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investissements', to='projects.projet'),
        ),
        migrations.AlterField(
            model_name='investissement',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE_PAIEMENT', 'En attente de paiement'), ('PAIEMENT_RECU', 'Paiement reçu'), ('CONFIRME', 'Confirmé par admin'), ('REJETE', 'Rejeté'), ('ANNULE', 'Annulé'), ('REMBOURSE', 'Remboursé')], default='EN_ATTENTE_PAIEMENT', max_length=30),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date_transaction',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='investissement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='investments.investissement'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='mode_paiement',
            field=models.CharField(blank=True, choices=[('ORANGE_MONEY', 'Orange Money'), ('MOOV_MONEY', 'Moov Money'), ('WAVE', 'Wave'), ('CARTE_BANCAIRE', 'Carte Bancaire'), ('VIREMENT', 'Virement Bancaire')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reference',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDEE', 'Validée'), ('ECHOUEE', 'Échouée'), ('ANNULEE', 'Annulée')], default='EN_ATTENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('INVESTISSEMENT', 'Investissement'), ('REMBOURSEMENT', 'Remboursement')], max_length=20),
        ),
    ]
