# Generated by Django 4.2.7 on 2026-01-09 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0004_alter_investissement_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investissement',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('PAIEMENT_RECU', 'Paiement reçu'), ('CONFIRME', 'Confirmé par admin'), ('REJETE', 'Rejeté'), ('ANNULE', 'Annulé'), ('REMBOURSE', 'Remboursé')], default='EN_ATTENTE', max_length=30),
        ),
    ]
