# Generated by Django 4.2.7 on 2025-10-13 18:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('telephone', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Format de téléphone invalide', regex='^\\+?[0-9]{8,15}$')], verbose_name='Téléphone')),
                ('profession', models.CharField(blank=True, max_length=100, verbose_name='Profession')),
                ('entreprise', models.CharField(blank=True, max_length=100, verbose_name='Entreprise')),
                ('experience', models.TextField(blank=True, verbose_name='Expérience')),
                ('date_inscription', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'inscription")),
                ('statut_compte', models.CharField(choices=[('ACTIF', 'Actif'), ('SUSPENDU', 'Suspendu'), ('BLOQUE', 'Bloqué')], default='ACTIF', max_length=20, verbose_name='Statut du compte')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'ordering': ['-date_inscription'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('INVESTISSEUR', 'Investisseur'), ('PROMOTEUR', 'Promoteur'), ('ADMINISTRATEUR', 'Administrateur')], max_length=20, verbose_name='Type de rôle')),
                ('statut', models.CharField(choices=[('EN_ATTENTE_VALIDATION', 'En attente de validation'), ('VALIDE', 'Validé'), ('REFUSE', 'Refusé'), ('SUSPENDU', 'Suspendu')], default='EN_ATTENTE_VALIDATION', max_length=25, verbose_name='Statut du rôle')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('role_actif', models.BooleanField(default=True, verbose_name='Rôle actif')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Rôle',
                'verbose_name_plural': 'Rôles',
                'unique_together': {('utilisateur', 'type')},
            },
        ),
    ]
