# Generated by Django 4.2.7 on 2025-11-24 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='administrateur_validateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles_valides', to=settings.AUTH_USER_MODEL, verbose_name='Administrateur validateur'),
        ),
        migrations.AddField(
            model_name='role',
            name='date_refus',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de refus'),
        ),
        migrations.AddField(
            model_name='role',
            name='date_suspension',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de suspension'),
        ),
        migrations.AddField(
            model_name='role',
            name='date_validation',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de validation'),
        ),
        migrations.AddField(
            model_name='role',
            name='motif_refus',
            field=models.TextField(blank=True, verbose_name='Motif de refus'),
        ),
        migrations.AddField(
            model_name='role',
            name='motif_suspension',
            field=models.TextField(blank=True, verbose_name='Motif de suspension'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='statut_compte',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente de validation'), ('ACTIF', 'Actif'), ('SUSPENDU', 'Suspendu'), ('BLOQUE', 'Bloqué')], default='EN_ATTENTE', max_length=20, verbose_name='Statut du compte'),
        ),
    ]
