# Generated by Django 4.2.7 on 2025-10-13 18:53

import apps.documents.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du document')),
                ('type', models.CharField(choices=[('JUSTIFICATIF_IDENTITE', "Justificatif d'identité"), ('JUSTIFICATIF_REVENU', 'Justificatif de revenu'), ('JUSTIFICATIF_FONDS', "Justificatif d'origine des fonds"), ('DOCUMENT_PROJET', 'Document de projet'), ('PLAN_FINANCIER', 'Plan financier'), ('PIECE_IDENTITE', "Pièce d'identité"), ('CONTRAT_SIGNE', 'Contrat signé'), ('RAPPORT_AVANCEMENT', "Rapport d'avancement")], max_length=25, verbose_name='Type de document')),
                ('fichier', models.FileField(upload_to=apps.documents.models.document_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png', 'gif'])], verbose_name='Fichier')),
                ('taille', models.BigIntegerField(verbose_name='Taille (bytes)')),
                ('date_telechargement', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de téléchargement')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDE', 'Validé'), ('REFUSE', 'Refusé')], default='EN_ATTENTE', max_length=15, verbose_name='Statut du document')),
                ('proprietaire_id', models.PositiveIntegerField(verbose_name='ID du propriétaire')),
                ('proprietaire_type', models.CharField(choices=[('utilisateur', 'Utilisateur'), ('projet', 'Projet')], max_length=15, verbose_name='Type de propriétaire')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('motif_refus', models.TextField(blank=True, verbose_name='Motif de refus')),
                ('administrateur_validateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_valides', to=settings.AUTH_USER_MODEL, verbose_name='Administrateur validateur')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-date_telechargement'],
            },
        ),
    ]
