# Generated by Django 4.2.7 on 2025-10-23 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('JUSTIFICATIF_IDENTITE', "Justificatif d'identité"), ('JUSTIFICATIF_REVENU', 'Justificatif de revenu'), ('JUSTIFICATIF_FONDS', "Justificatif d'origine des fonds"), ('STATUTS_ENTREPRISE', "Statuts d'entreprise"), ('DOCUMENT_PROJET', 'Document de projet'), ('PLAN_FINANCIER', 'Plan financier'), ('PIECE_IDENTITE', "Pièce d'identité"), ('CONTRAT_SIGNE', 'Contrat signé'), ('RAPPORT_AVANCEMENT', "Rapport d'avancement")], max_length=25, verbose_name='Type de document'),
        ),
    ]
