# Generated by Django 4.2.7 on 2025-10-13 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('contenu', models.TextField(verbose_name='Contenu')),
                ('type', models.CharField(choices=[('VALIDATION_COMPTE', 'Validation de compte'), ('VALIDATION_PROJET', 'Validation de projet'), ('NOUVEL_INVESTISSEMENT', 'Nouvel investissement'), ('MISE_A_JOUR_PROJET', 'Mise à jour de projet'), ('ALERTE_SYSTEME', 'Alerte système'), ('RAPPEL', 'Rappel'), ('CONFIRMATION_INVESTISSEMENT', "Confirmation d'investissement"), ('REFUS_INVESTISSEMENT', "Refus d'investissement"), ('PROJET_FINANCE', 'Projet entièrement financé'), ('ETAPE_TERMINEE', 'Étape terminée'), ('COMPTE_RENDU_PUBLIE', 'Compte rendu publié')], max_length=30, verbose_name='Type de notification')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('date_lecture', models.DateTimeField(blank=True, null=True, verbose_name='Date de lecture')),
                ('lue', models.BooleanField(default=False, verbose_name='Lue')),
                ('action_requise', models.BooleanField(default=False, verbose_name='Action requise')),
                ('lien_action', models.URLField(blank=True, verbose_name="Lien d'action")),
                ('investissement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='investments.investissement', verbose_name='Investissement concerné')),
                ('projet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='projects.projet', verbose_name='Projet concerné')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur destinataire')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['utilisateur', 'lue'], name='notificatio_utilisa_74632e_idx'), models.Index(fields=['date_creation'], name='notificatio_date_cr_1b0271_idx')],
            },
        ),
    ]
