# Generated by Django 4.2.7 on 2025-11-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('VALIDATION_COMPTE', 'Validation de compte'), ('VALIDATION_PROJET', 'Validation de projet'), ('NOUVEL_INVESTISSEMENT', 'Nouvel investissement'), ('MISE_A_JOUR_PROJET', 'Mise à jour de projet'), ('ALERTE_SYSTEME', 'Alerte système'), ('RAPPEL', 'Rappel'), ('CONFIRMATION_INVESTISSEMENT', "Confirmation d'investissement"), ('REFUS_INVESTISSEMENT', "Refus d'investissement"), ('PROJET_FINANCE', 'Projet entièrement financé'), ('ETAPE_TERMINEE', 'Étape terminée'), ('COMPTE_RENDU_PUBLIE', 'Compte rendu publié'), ('NOUVEAU_PROJET_A_VALIDER', 'Nouveau projet à valider')], max_length=30, verbose_name='Type de notification'),
        ),
    ]
