# Generated by Django 4.2.7 on 2025-11-07 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0002_alter_notification_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametreNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_projet_valide', models.BooleanField(default=True, verbose_name='Projet validé')),
                ('email_nouvel_investissement', models.BooleanField(default=True, verbose_name='Nouvel investissement')),
                ('email_objectif_atteint', models.BooleanField(default=True, verbose_name='Objectif de financement atteint')),
                ('email_nouveau_commentaire', models.BooleanField(default=True, verbose_name='Nouveau commentaire')),
                ('email_mise_a_jour', models.BooleanField(default=True, verbose_name='Mise à jour de la plateforme')),
                ('resume_quotidien', models.BooleanField(default=False, verbose_name='Résumé quotidien')),
                ('resume_hebdomadaire', models.BooleanField(default=True, verbose_name='Résumé hebdomadaire')),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parametres_notification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paramètre de notification',
                'verbose_name_plural': 'Paramètres de notification',
            },
        ),
    ]
